name: Pandoc Conversion

on: push

jobs:
    setup:
        runs-on: ubuntu-18.04
        outputs:
            matrix: ${{ steps.files_list.outputs.files }}
        steps:
            - uses: actions/checkout@v2
            - name: create file list
              id: files_list
              run: |
                cd reports
                echo "::set-output name=files::[$(printf '"%s", ' *.md)]"
    convert_to_pandoc:
        needs: [ setup ]
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                file: ${{fromJson(needs.setup.outputs.matrix)}}
        steps:
            - uses: actions/checkout@v2
            - name: Setup env vars
              run: |
                echo "OUTPUT=$(basename -s .md ${{matrix.file}})" >> $GITHUB_ENV
            - name: Create directories
              run: |
                rm -R generated
                mkdir -p generated/pdfs/
                mkdir -p generated/html/
            - name: Convert mk to pdf
              uses: docker://pandoc/latex:2.17
              with:
                  args: >
                      reports/${{ matrix.file }}
                      -f markdown
                      -t pdf
                      -s
                      --output=generated/pdfs/${{env.OUTPUT}}.pdf
            - name: Convert mk to html
              uses: docker://pandoc/latex:2.17
              with:
                  args: >
                      reports/${{ matrix.file }}
                      -f markdown
                      -t html
                      --mathml
                      -s
                      --output=generated/html/${{env.OUTPUT}}.html
            - name: Push to repo
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                
                git add generated/
                git commit -m "Push generated pdfs/html"
                git push
                    
                    